-- MySQL Script generated by MySQL Workbench
-- Tue Jun 11 11:29:56 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema moovit
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `moovit` ;

-- -----------------------------------------------------
-- Schema moovit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moovit` DEFAULT CHARACTER SET utf8 ;
USE `moovit` ;

-- -----------------------------------------------------
-- Table `moovit`.`competition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moovit`.`competition` ;

CREATE TABLE IF NOT EXISTS `moovit`.`competition` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `start_time` DATETIME NOT NULL,
  `details` LONGTEXT NULL,
  `adress` VARCHAR(255) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_training_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_training_user0`
    FOREIGN KEY (`user_id`)
    REFERENCES `moovit`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovit`.`feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moovit`.`feedback` ;

CREATE TABLE IF NOT EXISTS `moovit`.`feedback` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `duration` DATETIME NOT NULL,
  `global` ENUM('easy', 'medium', 'hard') NOT NULL,
  `difficulty` ENUM('easy', 'medium', 'hard') NOT NULL,
  `after` ENUM('tired', 'good', 'perfect') NOT NULL,
  `details` LONGTEXT NULL,
  `training_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_feedback_training1_idx` (`training_id` ASC) VISIBLE,
  CONSTRAINT `fk_feedback_training1`
    FOREIGN KEY (`training_id`)
    REFERENCES `moovit`.`training` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovit`.`sport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moovit`.`sport` ;

CREATE TABLE IF NOT EXISTS `moovit`.`sport` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` ENUM('fitness', 'running') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovit`.`template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moovit`.`template` ;

CREATE TABLE IF NOT EXISTS `moovit`.`template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `duration` DATETIME NULL,
  `details` LONGTEXT NULL,
  `user_id` INT NOT NULL,
  `sport_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_template_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_template_sport1_idx` (`sport_id` ASC) VISIBLE,
  CONSTRAINT `fk_template_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `moovit`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_template_sport1`
    FOREIGN KEY (`sport_id`)
    REFERENCES `moovit`.`sport` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovit`.`tip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moovit`.`tip` ;

CREATE TABLE IF NOT EXISTS `moovit`.`tip` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `content` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovit`.`training`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moovit`.`training` ;

CREATE TABLE IF NOT EXISTS `moovit`.`training` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `duration` VARCHAR(45) NOT NULL,
  `details` LONGTEXT NULL,
  `time_of_day` ENUM('morning', 'afternoon', 'evening') NULL,
  `is_completed` TINYINT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_training_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_training_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `moovit`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovit`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moovit`.`user` ;

CREATE TABLE IF NOT EXISTS `moovit`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `level` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovit`.`user_has_sport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moovit`.`user_has_sport` ;

CREATE TABLE IF NOT EXISTS `moovit`.`user_has_sport` (
  `user_id` INT NOT NULL,
  `sport_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `sport_id`),
  INDEX `fk_user_has_sport_sport1_idx` (`sport_id` ASC) VISIBLE,
  INDEX `fk_user_has_sport_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_sport_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `moovit`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_sport_sport1`
    FOREIGN KEY (`sport_id`)
    REFERENCES `moovit`.`sport` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
